### ISSUE TITLE
Can't access the http://localhost:8080/OSLC4JBugzilla/services/catalog/singleton

### ISSUE THREAD

**Issue by onsDridi** [OSLC/developing-oslc-applications#37]
Hello, 

I'm trying to understand the OSLC protocol and I followed this tutorial : https://oslc.github.io/developing-oslc-applications/integrating_products_with_oslc/running_the_examples . After Starting the OSLC4J Bugzilla adapter, I can't access the uri :  http://localhost:8080/OSLC4JBugzilla/services/catalog/singleton . I got this error instead : 
<img width="592" alt="Capture d’écran 2022-09-14 à 22 59 45" src="https://user-images.githubusercontent.com/11782910/190261802-6135f406-3add-4e76-b711-becc94bfbf48.png">

Do you have any idea about how to fix this issue ? 
Thanks

**Comment by jadelkhoury** [comment]
What do you see in the logs?
Can you hit http://localhost:8080/OSLC4JBugzilla or http://localhost:8080?

**Comment by onsDridi** [comment]
For both URI I don't have access. Here is a preview of my log : 

[INFO] restarting o.m.j.p.JettyWebAppContext{/OSLC4JBugzilla,[file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/, file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/]},file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/
[INFO] javax.el.BeanELResolver purged
[INFO] stopped o.m.j.p.JettyWebAppContext{/OSLC4JBugzilla,[file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/, file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/]},file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/
[INFO] Webapp source directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/classes
[INFO] Added extra scan target:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/WebContent
[INFO] Context path = /OSLC4JBugzilla
[INFO] Tmp directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] Adding overlay for war project artifact org.eclipse.lyo.server:oauth-webapp:war:2.2.0
[INFO] web.xml file = file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp
[INFO] Unpacking overlay: jar:file:/Users/od/.m2/repository/org/eclipse/lyo/server/oauth-webapp/2.2.0/oauth-webapp-2.2.0.war!/
[INFO] Adding overlay: file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
bugzilla_uri: http://localhost/bugzilla
admin: admin
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Restart completed at Thu Sep 15 12:34:40 CEST 2022
[INFO] restarting o.m.j.p.JettyWebAppContext{/OSLC4JBugzilla,[file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/, file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/]},file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/
[INFO] javax.el.BeanELResolver purged
[INFO] stopped o.m.j.p.JettyWebAppContext{/OSLC4JBugzilla,[file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/, file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/]},file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/
[INFO] Webapp source directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/classes
[INFO] Added extra scan target:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/WebContent
[INFO] Context path = /OSLC4JBugzilla
[INFO] Tmp directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] Adding overlay for war project artifact org.eclipse.lyo.server:oauth-webapp:war:2.2.0
[INFO] web.xml file = file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp
[INFO] Reconfiguring scanner after change to pom.xml ...
[INFO] Unpacking overlay: jar:file:/Users/od/.m2/repository/org/eclipse/lyo/server/oauth-webapp/2.2.0/oauth-webapp-2.2.0.war!/
[INFO] Adding overlay: file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
bugzilla_uri: http://localhost/bugzilla
admin: admin
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Restart completed at Thu Sep 15 12:35:18 CEST 2022
[INFO] restarting o.m.j.p.JettyWebAppContext{/OSLC4JBugzilla,[file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/, file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/]},file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/
[INFO] javax.el.BeanELResolver purged
[INFO] stopped o.m.j.p.JettyWebAppContext{/OSLC4JBugzilla,[file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/, file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/]},file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/
[INFO] Webapp source directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/classes
[INFO] Added extra scan target:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/WebContent
[INFO] Context path = /OSLC4JBugzilla
[INFO] Tmp directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] Adding overlay for war project artifact org.eclipse.lyo.server:oauth-webapp:war:2.2.0
[INFO] web.xml file = file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/src/main/webapp
[INFO] Reconfiguring scanner after change to pom.xml ...
[INFO] Unpacking overlay: jar:file:/Users/od/.m2/repository/org/eclipse/lyo/server/oauth-webapp/2.2.0/oauth-webapp-2.2.0.war!/
[INFO] Adding overlay: file:/Users/od/git/lyo.docs/lyo-rest-workshop/Lab6/target/tmp/oauth-webapp-2_2_0_war/
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
bugzilla_uri: http://localhost/bugzilla
admin: admin
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Restart completed at Thu Sep 15 12:36:57 CEST 2022

**Comment by onsDridi** [comment]
Hello, 

Now I can access the page but it's empty . here's a look at my logs : 

PWC6199: Generated servlet error:
Target option 1.5 is no longer supported. Use 1.6 or later.


	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:374)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:492)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:378)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:276)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
	at org.eclipse.lyo.oslc4j.bugzilla.services.ServiceProviderCatalogService.getHtmlServiceProvider(ServiceProviderCatalogService.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
	at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.handlers.CreateInvocationParametersHandler.handleRequest(CreateInvocationParametersHandler.java:54)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleSubResourceMethod(FindResourceMethodHandler.java:183)
	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleRequest(FindResourceMethodHandler.java:110)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.handlers.FindRootResourceHandler.handleRequest(FindRootResourceHandler.java:95)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.handlers.HeadMethodHandler.handleRequest(HeadMethodHandler.java:53)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.handlers.OptionsMethodHandler.handleRequest(OptionsMethodHandler.java:46)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.handlers.SearchResultHandler.handleRequest(SearchResultHandler.java:33)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.log.ResourceInvocation.handleRequest(ResourceInvocation.java:92)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.internal.log.Requests.handleRequest(Requests.java:76)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:63)
	at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:48)
	at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:207)
	at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)
	at org.apache.wink.server.internal.servlet.RestServlet.service(RestServlet.java:119)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at org.eclipse.lyo.oslc4j.bugzilla.servlet.CredentialsFilter.doFilter(CredentialsFilter.java:151)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by onsDridi** [comment]
It was a java version problem ! I was using java 11. I used Java 8 instead and it worked for me 

Thank you

**Comment by jadelkhoury** [comment]
Good to hear.
Please feel free to use our forum https://forum.open-services.net/ so you can reach out to a broader community about any questions.
Will close this issue now.
